apiVersion: v1
kind: Service
metadata:
  name: mercados-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    mercados: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001