version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mercados
      - POSTGRES_USER=mercados
      - POSTGRES_PASSWORD=mercados
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - ../dkdata/postgres:/var/lib/postgresql/data
  nginx:
    image: nginx
    network_mode: "host"
    volumes:
      - ../nginx/default_local:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
