# Generated by Django 4.0.5 on 2023-03-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produto_nome_alter_produto_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='peso_g',
        ),
        migrations.AddField(
            model_name='mercado',
            name='filial',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidades',
            field=models.IntegerField(default=1),
        ),
    ]
