# Generated by Django 4.0.5 on 2023-04-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_unacced_e_trigram"),
    ]

    operations = [
        migrations.AddField(
            model_name="mercado",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mercado",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
